version: '3'

services:
  web:
    build: .
    command: gunicorn ag.wsgi:application --bind 0.0.0.0:9001
#    command: python3 manage.py runserver 0.0.0.0:8001
    volumes:
      - ./:/usr/src/app/
    ports:
      - 9001:9001


